services:
  db:
    image: postgres:13 # Define a versão do PostgreSQL
    container_name: arquivagas_db # Nome do contêiner
    # restart: unless-stopped # Reinicia o contêiner se ele parar
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Nome do usuário do banco de dados
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Senha do usuário do banco de dados
      POSTGRES_DB: ${POSTGRES_DB} # Nome do banco de dados que será criado
    ports:
      - "${POSTGRES_PORT}:5432" # Porta de mapeamento (local:container)
    # networks:
    #   - network
    volumes:
      - postgres_arqvagas_data:/var/lib/postgresql/data # Volume para persistência de dados

  app:
    build: .
    container_name: nestjs_container
    # restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3333:3333"
    # networks:
    #   - network
    # volumes:
    #   - .:/app
    volumes:
      - .:/app
    command: ["app", "-wait", "tcp://db:5432", "-timeout", "60s", "yarn", "start:dev"]
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.backend.rule=Host(`api.localhost`)"
    #   - "traefik.http.routers.backend.entrypoints=web"
    # command: ["yarn", "start:prod"]

volumes:
  postgres_arqvagas_data:
    driver: local # Driver do Docker para volumes persistentes
 
# networks:
#   network:
#     driver: bridge